POST http://localhost:8080/events
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiZXhwIjoxNzc0NDU3OTcwLCJ1c2VySWQiOjF9.F7WN4iBB2xhmtc1pqFiC3gncgjnsv3wwAmzfRU36xW4

{
    "name": "Test Event",
    "description": "Another Test Event!!!!",
    "location": "Test Location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}