DELETE http://localhost:8080/events/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsImV4cCI6MTc3NDQ1NDc0OCwidXNlcklkIjoyfQ.zfzlD0vrQLMkBXEYR-RhQuvabmU2FraKMTdVPAd9AMo